version: "3"

services:
  testdb:
    image: postgres:11.2-alpine
    container_name: testdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: krispcall
